App.constant("ContextualInformationConstants", {
	CONTEXTUAL_INFORMATION_SERVICE_ID: 83,
	CONTEXTUAL_INFORMATION_DOMAIN_ID: 100,
	CONTEXTUAL_INFORMATION_BUSINESS_ID: 1,
	CONTEXTUAL_INFORMATION_CHANNEL_ID: 1,
	CONTEXTUAL_INFORMATION_CLIENT_ID: 1,
	CONTEXTUAL_INFORMATION_REQUEST_CLIENT_ID: 123,
	CONTEXTUAL_INFORMATION_APPLICATION_ID: 55,
	CONTEXTUAL_INFORMATION_API_URL: "http://148.250.45.88:8026"
});